<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Vocabulary Books</name>
   <tag></tag>
   <elementGuidId>90ee7ec3-4e7a-41c9-9afd-1508a9c672f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='premadeLessonsMenuContainer']/ul/li/menu-item-popover/div/popover/div/ng-transclude/popover-content/ng-transclude/div/ng-transclude/div/div/desktop-menu-item/ul/li[7]/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = '/#!/premadeLessons/raz/1081' and (text() = ' Vocabulary Books  ' or . = ' Vocabulary Books  ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdownNav_pageLabel ng-binding</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-href</name>
      <type>Main</type>
      <value>/#!/premadeLessons/raz/1081</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>::$ctrl.getListItemLinkClass($first, $last)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>$ctrl.onClick()</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-keydown</name>
      <type>Main</type>
      <value>$ctrl.onKeyDown($event)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/#!/premadeLessons/raz/1081</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Vocabulary Books  </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;premadeLessonsMenuContainer&quot;)/ul[@class=&quot;dropdownNav_categoryList&quot;]/li[@class=&quot;dropdownNav_category ng-scope&quot;]/menu-item-popover[@class=&quot;ng-isolate-scope&quot;]/div[1]/popover[@class=&quot;popover-block popover-static ng-scope ng-isolate-scope&quot;]/div[@class=&quot;popover active&quot;]/ng-transclude[1]/popover-content[@class=&quot;ng-scope ng-isolate-scope is-linked&quot;]/ng-transclude[@class=&quot;ng-scope dropdownNav_flyout&quot;]/div[@class=&quot;dropdownNav_panel ng-scope&quot;]/ng-transclude[1]/div[@class=&quot;b-columns is-variable is-8 ng-scope&quot;]/div[@class=&quot;b-column is-narrow&quot;]/desktop-menu-item[@class=&quot;box marginB4 ng-scope ng-isolate-scope&quot;]/ul[@class=&quot;dropdownNav_pageList ng-scope&quot;]/li[@class=&quot;ng-scope&quot;]/a[@class=&quot;dropdownNav_pageLabel ng-binding&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='premadeLessonsMenuContainer']/ul/li/menu-item-popover/div/popover/div/ng-transclude/popover-content/ng-transclude/div/ng-transclude/div/div/desktop-menu-item/ul/li[7]/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Vocabulary Books')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shared Reading'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fiction Series'])[1]/following::a[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Raz-Plus ELL Edition'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ELL Language Skill Packs'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Vocabulary Books']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/#!/premadeLessons/raz/1081')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//desktop-menu-item/ul/li[7]/a</value>
   </webElementXpaths>
</WebElementEntity>
