<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Preview</name>
   <tag></tag>
   <elementGuidId>727fe79f-ca3c-41d2-86ba-1287f2319e23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='drawer_3903']/premade-lesson-card/div/div[2]/lesson-card-overview/div/div[3]/div/div[2]/popover/div/ng-transclude/popover-target/button/ng-transclude/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.resourceDrawer_link.fauxLink.ng-scope</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>resourceDrawer_link fauxLink ng-scope</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{'is-last': $ctrl.viewOnly}</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Preview</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;drawer_3903&quot;)/premade-lesson-card[@class=&quot;ng-scope ng-isolate-scope&quot;]/div[@class=&quot;resourceDrawer ng-scope&quot;]/div[2]/lesson-card-overview[@class=&quot;ng-isolate-scope&quot;]/div[@class=&quot;b-columns is-gapless is-multiline is-reversed is-mobile&quot;]/div[@class=&quot;b-column is-4&quot;]/div[@class=&quot;resourceDrawer_section&quot;]/div[@class=&quot;resourceDrawer_links&quot;]/popover[@class=&quot;ng-isolate-scope&quot;]/div[1]/ng-transclude[1]/popover-target[@class=&quot;ng-scope ng-isolate-scope&quot;]/button[@class=&quot;popover-target ng-isolate-scope&quot;]/ng-transclude[1]/button[@class=&quot;resourceDrawer_link fauxLink ng-scope&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='drawer_3903']/premade-lesson-card/div/div[2]/lesson-card-overview/div/div[3]/div/div[2]/popover/div/ng-transclude/popover-target/button/ng-transclude/button</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Printable Resources'])[1]/following::button[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assign'])[1]/following::button[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Options'])[1]/preceding::button[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download'])[1]/preceding::button[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Preview']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/popover/div/ng-transclude/popover-target/button/ng-transclude/button</value>
   </webElementXpaths>
</WebElementEntity>
